using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using TestsGenerator.IO;

[TestClass]
public class ClassWriterTestTest
{
    [TestMethod]
    public void Write_Test_Test()
    {
        ClassReader r = new ClassReader();
        Assert.Fail("autogenerated");
    }
}